[package]
name = "polkapad-distributor"
version = "0.1.0"
authors = ["Polkapad"]
edition = "2021"
license = "GPL-3.0"

[dependencies]
gstd = { git = "https://github.com/gear-tech/gear.git", branch = "stable" }
codec = { package = "parity-scale-codec", version = "3.2.1", default-features = false }
ft-io = { git = "https://github.com/gear-dapps/fungible-token.git", tag = "0.1.3" }
scale-info = { version = "2.3.1", default-features = false }
hashbrown = "0.13.1"

[dev-dependencies]
gstd = { git = "https://github.com/gear-tech/gear.git", branch = "stable", features = ["debug"] }
gtest = { git = "https://github.com/gear-tech/gear.git", branch = "stable" }
sp-core = { git = "https://github.com/gear-tech/substrate.git", branch = "gear-stable" }
gclient = { git = "https://github.com/gear-tech/gear.git", branch = "stable" }
tokio = "1"

[build-dependencies]
gear-wasm-builder = { git = "https://github.com/gear-tech/gear.git", branch = "stable" }

[patch.crates-io]
# Two dependecies below goes for subxt v0.22.0
sp-core = { git = "https://github.com/gear-tech/substrate.git", branch = "gear-stable" }
sp-runtime = { git = "https://github.com/gear-tech/substrate.git", branch = "gear-stable" }